name: Build LDAP SDK

on: [push, pull_request]

env:
  BASE_IMAGE: ${{ vars.BASE_IMAGE || 'registry.fedoraproject.org/fedora:latest' }}
  COPR_REPO: ${{ vars.COPR_REPO || '@pki/master' }}

jobs:
  build:
    name: Building LDAP SDK
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        id: cache-buildx
        uses: actions/cache@v3
        with:
          key: buildx-${{ hashFiles('ldapjdk.spec') }}
          path: /tmp/.buildx-cache

      - name: Build ldapjdk-deps image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            COPR_REPO=${{ env.COPR_REPO }}
          tags: ldapjdk-deps
          target: ldapjdk-deps
          cache-to: type=local,dest=/tmp/.buildx-cache
        if: steps.cache-buildx.outputs.cache-hit != 'true'

      - name: Build ldapjdk-builder-deps image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            COPR_REPO=${{ env.COPR_REPO }}
          tags: ldapjdk-builder-deps
          target: ldapjdk-builder-deps
          cache-to: type=local,dest=/tmp/.buildx-cache
        if: steps.cache-buildx.outputs.cache-hit != 'true'

      - name: Build ldapjdk-builder image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            COPR_REPO=${{ env.COPR_REPO }}
          tags: ldapjdk-builder
          target: ldapjdk-builder
          cache-from: type=local,src=/tmp/.buildx-cache
          outputs: type=docker,dest=ldapjdk-builder.tar

      - name: Store ldapjdk-builder image
        uses: actions/cache@v3
        with:
          key: ldapjdk-builder-${{ github.sha }}
          path: ldapjdk-builder.tar

      - name: Build ldapjdk-dist image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            COPR_REPO=${{ env.COPR_REPO }}
          tags: ldapjdk-dist
          target: ldapjdk-dist
          cache-from: type=local,src=/tmp/.buildx-cache
          outputs: type=docker,dest=ldapjdk-dist.tar

      - name: Store ldapjdk-dist image
        uses: actions/cache@v3
        with:
          key: ldapjdk-dist-${{ github.sha }}
          path: ldapjdk-dist.tar

      - name: Build ldapjdk-runner image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            COPR_REPO=${{ env.COPR_REPO }}
          tags: ldapjdk-runner
          target: ldapjdk-runner
          cache-from: type=local,src=/tmp/.buildx-cache
          outputs: type=docker,dest=ldapjdk-runner.tar

      - name: Store ldapjdk-runner image
        uses: actions/cache@v3
        with:
          key: ldapjdk-runner-${{ github.sha }}
          path: ldapjdk-runner.tar
